/**
 * Generates the 5 Guild-hosted guard agents from the game's own config, so the prompts never drift.
 *
 *   export PATH="$HOME/.nvm/versions/node/v22.18.0/bin:$PATH"
 *   npx tsx guild/generate.ts
 *
 * Source of truth: server/guards.ts (system prompts, tools) and shared/levels.ts (names, topics).
 * Output: guild/agents/<slug>/ with the same layout `guild agent init --template LLM` creates
 * (agent.ts, markdown.d.ts, package.json, tsconfig.json, README.md, .gitignore). guild.json is
 * managed by the Guild CLI and is created by publish.sh, never by hand.
 *
 * The Guild runtime only allows imports from @guildai/agents-sdk, zod and @guildai-services/*, so
 * every generated agent.ts imports @guildai/agents-sdk only, with the prompt inlined as a literal.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { GUARDS } from '../server/guards';
import type { GuardContext } from '../server/guardTypes';
import { LEVELS } from '../shared/levels';

/** Fixed demo context: the live game generates a random passphrase per player. */
const DEMO_CTX: GuardContext = { passphrase: 'WOBBLY-PICKLE', plugin: null, playerName: 'Player' };
const LLM_PREFERENCES = [{ provider: 'anthropic', model: 'claude-haiku-4-5' }];
const SDK_VERSION = '^0.6.0';
const ZOD_VERSION = '~4.3.0';

const here = dirname(fileURLToPath(import.meta.url));
const agentsDir = join(here, 'agents');

export function slugFor(guardName: string): string {
  return guardName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/** Renders the simulated tools as plain text, since Guild llmAgents here get `tools: {}`. */
function toolsSection(level: number): string {
  const tools = GUARDS[level].tools(DEMO_CTX);
  if (tools.length === 0) return 'You have no tools. You can only talk.';
  const lines = tools.map((t) => `- ${t.name}: ${t.description ?? ''} Input JSON schema: ${JSON.stringify(t.input_schema)}`);
  return [
    'You have these tools:',
    ...lines,
    'To use one, reply with a line CALL <tool>(<json>), where <json> matches that tool\'s input schema.',
    'The game engine runs the tool and answers with a line RESULT <text>.',
  ].join('\n');
}

function agentTs(level: number): string {
  const info = LEVELS[level - 1];
  const systemPrompt = `${GUARDS[level].systemPrompt(DEMO_CTX)}\n\n${toolsSection(level)}`;
  const description = `Break the Guard, level ${info.id}: ${info.guardName} guards ${info.title}. Teaches ${info.topic}.`;
  return `// GENERATED by guild/generate.ts from server/guards.ts and shared/levels.ts. Do not edit by hand.
// Level ${info.id}: ${info.guardName} (${info.topic}). Demo passphrase: ${DEMO_CTX.passphrase}.
import { llmAgent } from "@guildai/agents-sdk"

const systemPrompt = ${JSON.stringify(systemPrompt)}

export default llmAgent({
  description: ${JSON.stringify(description)},
  tools: {},
  systemPrompt,
  mode: "multi-turn",
  llmPreferences: [${LLM_PREFERENCES.map((p) => `{ provider: ${JSON.stringify(p.provider)}, model: ${JSON.stringify(p.model)} }`).join(', ')}],
})
`;
}

function packageJson(slug: string): string {
  return (
    JSON.stringify(
      {
        name: `break-the-guard-${slug}`,
        version: '0.1.0',
        private: true,
        type: 'module',
        main: 'agent.ts',
        dependencies: { '@guildai/agents-sdk': SDK_VERSION, zod: ZOD_VERSION },
        devDependencies: { typescript: '^5.6.0' },
      },
      null,
      2,
    ) + '\n'
  );
}

const TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      esModuleInterop: true,
    },
    include: ['agent.ts', 'markdown.d.ts'],
  },
  null,
  2,
)}\n`;

const MARKDOWN_D_TS = `declare module "*.md" {
  const content: string
  export default content
}
`;

const GITIGNORE = 'node_modules\ndist\n.env\n';

function readme(level: number, slug: string): string {
  const info = LEVELS[level - 1];
  return `# ${info.guardName}: ${info.title}

Break the Guard, level ${info.id}. Topic: **${info.topic}**.

${info.concept.what}

- Generated by \`guild/generate.ts\` from \`server/guards.ts\`. Edit the game config, then regenerate.
- Model: claude-haiku-4-5 (Anthropic), multi-turn, no platform tools. Game tools are simulated and described in the prompt.
- Demo passphrase: \`${DEMO_CTX.passphrase}\`.

Try: \`guild agent test "${info.hints[2].replace(/"/g, "'")}"\`

Publish: see \`guild/README.md\` (\`bash guild/publish.sh ${slug}\`).
`;
}

for (const info of LEVELS) {
  const slug = slugFor(info.guardName);
  const dir = join(agentsDir, slug);
  mkdirSync(dir, { recursive: true });
  const files: Record<string, string> = {
    'agent.ts': agentTs(info.id),
    'markdown.d.ts': MARKDOWN_D_TS,
    'package.json': packageJson(slug),
    'tsconfig.json': TSCONFIG,
    'README.md': readme(info.id, slug),
    '.gitignore': GITIGNORE,
  };
  for (const [name, content] of Object.entries(files)) writeFileSync(join(dir, name), content);
  console.log(`wrote guild/agents/${slug}/ (${Object.keys(files).length} files)`);
}
